- name: "Create and delete file"
  hosts: localhost
  tasks:
   - name: "creating a file"
     file: 
       path: $HOME/noonstg/file/fuckyou.txt
       state: touch
     register: touch_output
   - debug: 
      var=touch_output

   - name: "deleting a file"
     file:
       path: $HOME/noonstg/file/fuckyou.txt
       state: absent
     register: touch_delete

   - debug:
      var=touch_delete
