- name: "Deleteing file uising anisble"
  hosts: localhost
  tasks:
    - name: "removing file using anisble"
      file:
        path: "$HOME/{{ item }}"
        state: absent
      loop:
         - nandhu_dir
         - kumar_dir
         - anvar_dir
